import fs from 'fs';
import path from 'path';
import * as d3Geo from 'd3-geo';

function generate() {
  const geojsonPath = path.resolve(process.cwd(), 'data/geo/bangladesh-districts.geojson');
  const geojson = JSON.parse(fs.readFileSync(geojsonPath, 'utf8'));

  const width = 800;
  const height = 1000;
  const projection = d3Geo
    .geoMercator()
    .fitExtent([[25, 25], [width - 25, height - 25]], geojson);
  const pathGenerator = d3Geo.geoPath().projection(projection);

  interface DistrictMeta {
    id: string;
    name: string;
    nameBn: string;
    divisionId: string;
    slug: string;
  }

  const districtsPath = path.resolve(process.cwd(), 'data/districts.json');
  const districts: DistrictMeta[] = JSON.parse(fs.readFileSync(districtsPath, 'utf8'));
  const distMap = new Map<string, DistrictMeta>(districts.map((d) => [d.id, d]));

  const pathDataList = geojson.features.map((feat: any) => {
    const meta = distMap.get(feat.id);
    const centroid = pathGenerator.centroid(feat);
    const d = pathGenerator(feat);

    return {
      id: feat.id,
      name: meta?.name || feat.properties.name,
      nameBn: meta?.nameBn || feat.properties.nameBn,
      divisionId: meta?.divisionId || feat.properties.divisionId,
      slug: meta?.slug || feat.properties.slug,
      centroid: [
        Math.round(centroid[0] * 100) / 100,
        Math.round(centroid[1] * 100) / 100,
      ],
      d,
    };
  });

  const content = `// Generated by scripts/generate-paths.ts
// Do not edit manually.
import { DistrictPathData } from './types';

export const MAP_VIEWBOX = '0 0 800 1000';
export const MAP_WIDTH = 800;
export const MAP_HEIGHT = 1000;

export const DISTRICT_PATHS: DistrictPathData[] = ${JSON.stringify(pathDataList, null, 2)};

export const DISTRICT_PATH_MAP = new Map<string, DistrictPathData>(
  DISTRICT_PATHS.map((p) => [p.id, p])
);
`;

  fs.mkdirSync(path.resolve(process.cwd(), 'src/map'), { recursive: true });
  fs.writeFileSync(path.resolve(process.cwd(), 'src/map/paths.ts'), content);
  console.log(`Generated src/map/paths.ts with ${pathDataList.length} district paths.`);
}

generate();
